[package]
name = "consumer"
version = "0.1.0"
edition = "2024"
authors = ["Norbert Ha≈Ñderek <norbert.handerek03@gmail.com>"]

[dependencies]
common = { path = "../common" }
tokio = { version = "1.44.2", features = ["full"] }
nalgebra = "0.33.2"
approx = "0.5.1"